# Generated by Django 4.2.3 on 2023-07-17 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfollow",
            options={
                "verbose_name": "User Follow",
                "verbose_name_plural": "User Follows",
            },
        ),
    ]
