# Generated by Django 4.2.3 on 2023-07-19 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_userfollow_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFollow",
        ),
    ]
